# Generated by Django 4.2.6 on 2023-11-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_bottom_text_alter_post_meme_template_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bottom_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meme_template_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='top_text',
        ),
    ]
